#!/home/tide/.tidenv/bin/python3
import cgi, cgitb
from datetime import datetime
import sqlite3
import smtplib
import secrets

form = cgi.FieldStorage()
valkey = form["valkey"].value
timeformat = "%Y-%m-%d %H:%M:%S"
curtime = datetime.now()
dbtime = str(curtime)[:-7]
def change_password(valkey):
   print ("Content-type:text/html\r\n\r\n")
   print ('<html>')
   print('<style type="text/css">')
   print('.center-screen {')
   print('      display: flex;')
   print('      flex-direction: column;')
   print('      justify-content: center;')
   print('      align-items: center;')
   print('      text-align: center;')
   print('}')
   print('.dirtab {')
   print('   text-indent: 33%;')
   print('}')
   print('.navbar {')
   print('  max-width: 560px;')
   print('  margin: 0 auto 14px auto;')
   print('  text-align: center;')
   print('}')
   print('.navbar button {')
   print('  font-family: "Arial", "Helvetica", sans-serif;')
   print('  font-size: 1em;')
   print('  font-weight: bold;')
   print('  color: #FFFFFF;')
   print('  background-color: #1B3A5C;')
   print('  border: 2px solid #000000;')
   print('  border-radius: 6px;')
   print('  padding: 8px 18px;')
   print('  margin: 0 8px;')
   print('  cursor: pointer;')
   print('}')
   print('</style>')
   print('<head>')
   print('   <title>Tide Alerts</title>')
   print('<script language = "Javascript">')
   print('   function validit(form) {')
   print('      var confirmit = true;')
   print('      var passwd1 = document.getElementsByName("passwd1")[0].value;')
   print('      var passwd2 = document.getElementsByName("passwd2")[0].value;')
   print('      if (passwd1 != passwd2) {')
   print('         alert("passwords do not match");')
   print('         confirmit = false;')
   print('      }')
   print('      return confirmit;')
   print('   }')
   print('</script>')
   print('</head>')
   print('   <body bgcolor="black"><font size = "4">')
   print('   <div class="center-screen">')
   print('    <div class="navbar">')
   print('      <a href="/index.html"><button type="button">Home</button></a>')
   print('      <a href="/alertlogin.html"><button type="button">Return to Login</button></a>')
   print('    </div>')
   print('    <span style="border:8px double #1B3A5C; box-sizing: border-box; width: 560px; padding: 25px; background-color: #E3F1F0;">')
   print('    <img src="/webimage.png"')
   print('         style="width: 480px; height: 300px; object-fit: contain; background-color: #FFFFFF;"/>')
   print('      <h1 style="width: 480px; margin: 0 auto; text-align: center; font-size: 25px; font-color: black; padding: 4px;">Tide Alert Change Password</h1>')
   print('      <p>')
   print('      <form  action="/cgi-bin/reset-pw-1.cgi" method="post" onsubmit="return validit(this);">')
   print(f'     <input type="hidden" name="valkey" id="valkey" value="{valkey}"><br><br>')
   print('      <label for="passwd1">Enter new password:</label>')
   print('      <input type="password" name="passwd1" id="passwd1" minlength="8" pattern="[A-Za-z0-9]{8-16}" autocomplete="new-password" required><br><br>')
   print('      <label for="passwd2">Confirm new password:</label>')
   print('      <input type="password" name="passwd2" id="passwd2" minlength="8" pattern="[A-Za-z0-9]{8-16}" autocomplete="new-password" required><br><br>')
   print('      <input type="submit" value="Submit">')
   print('      </form>')
   print('      </p>')
   print('    </span>')
   print('   </div>')
   print('   </font></body>')
   print('</html>')
change_password(valkey)
